const SAINTS = [
    {
        MONTH: 'Enero',
        DAYS: [
            { name: 'Santa Maria', holiday: { title: 'Año Nuevo', icon: 'fas fa-glass-cheers' } },
            { name: 'Basilio' },
            { name: 'Genoveva' },
            { name: 'Rigoberto' },
            { name: 'Amelia' },
            { name: 'Epifania', holiday: { title: 'Santos Reyes', icon: 'fas fa-crown' } },
            { name: 'Raymundo' },
            { name: 'Gudula' },
            { name: 'Eulogio' },
            { name: 'Maria Dolores' },
            { name: 'Hortencia' },
            { name: 'Benito' },
            { name: 'Hilario' },
            { name: 'Félix' },
            { name: 'Mauro' },
            { name: 'Marcelo' },
            { name: 'Antonio Abad' },
            { name: 'Prisca' },
            { name: 'Arsenio' },
            { name: 'Fabián' },
            { name: 'Ines' },
            { name: 'Laura' },
            { name: 'Ildefonso' },
            { name: 'Paz' },
            { name: 'Pablo Apóstol' },
            { name: 'Timoteo' },
            { name: 'Ángela' },
            { name: 'Tomás de Aquino' },
            { name: 'Constancio' },
            { name: 'Martina' },
            { name: 'Juan Bosco' }
        ]
    },
    {
        MONTH: 'Febrero',
        DAYS: [
            { name: 'Cecilio' },
            { name: 'Purificación' },
            { name: 'Verónica' },
            { name: 'Gilberto' },
            { name: 'Felipe de Jesús' },
            { name: 'Gonzalo' },
            { name: 'Adalberto' },
            { name: 'Josefina' },
            { name: 'Apolonia' },
            { name: 'Escolástica' },
            { name: 'Mária de Lourdes' },
            { name: 'Eulalia' },
            { name: 'Benigno' },
            { name: 'San Valentín', holiday: { title: 'San Valentín', icon: 'fas fa-heart' } },
            { name: 'Onésimo' },
            { name: 'Juliana' },
            { name: 'Teodoro' },
            { name: 'Eladio' },
            { name: 'Álvaro' },
            { name: 'Eleuterio' },
            { name: 'Pedro Damián' },
            { name: 'Pascacio' },
            { name: 'Policarpo' },
            { name: 'Sergio' },
            { name: 'Valerio' },
            { name: 'Alejandro' },
            { name: 'Gabriel' },
            { name: 'Leandro' },
            { name: 'Dositeo' }
        ]
    },
    {
        MONTH: 'Marzo',
        DAYS: [
            { name: 'David' },
            { name: 'Simplicio' },
            { name: 'Emeterio' },
            { name: 'Casimiro' },
            { name: 'Adriano' },
            { name: 'Pablo' },
            { name: 'Perpetua' },
            { name: 'Veremundo', holiday: { title: 'Dia Internacional de la Mujer', icon: 'fas fa-female' } },
            { name: 'Francisca Romana' },
            { name: 'Maria Eugenia' },
            { name: 'Ramiro' },
            { name: 'Teófanes' },
            { name: 'Rodrigo' },
            { name: 'Matilde' },
            { name: 'Luisa' },
            { name: 'Abraham' },
            { name: 'Patricio' },
            { name: 'Salvador' },
            { name: 'San José' },
            { name: 'Hipólito' },
            { name: 'Benita' },
            { name: 'Lea' },
            { name: 'Toribio' },
            { name: 'Epigmenio' },
            { name: 'Anunciación del Señor' },
            { name: 'Braulio' },
            { name: 'Ruperto' },
            { name: 'Sixto' },
            { name: 'Eustasio' },
            { name: 'Zósimo' },
            { name: 'Benjamin' }
        ]
    },
    {
        MONTH: 'Abril',
        DAYS: [
            { name: 'Hugo' },
            { name: 'Ofelia' },
            { name: 'Ricardo' },
            { name: 'Isídoro' },
            { name: 'Geraldo' },
            { name: 'Gala' },
            { name: 'Juan Bautista', holiday: { title: 'Día Mundial del Libro', icon: 'fas fa-heartbeat' } },
            { name: 'Julia' },
            { name: 'Casilda' },
            { name: 'Ezequiel' },
            { name: 'Estanislao' },
            { name: 'Julio' },
            { name: 'Hermenegildo' },
            { name: 'Lidia' },
            { name: 'César' },
            { name: 'Engracia' },
            { name: 'Roberto' },
            { name: 'Perfecto' },
            { name: 'Crescencio' },
            { name: 'Simón' },
            { name: 'San Anselmo' },
            { name: 'Sotero' },
            { name: 'Jorge', holiday: { title: 'Día Mundial del Libro', icon: 'fas fa-book' } },
            { name: 'Fidel' },
            { name: 'San Marcos Evangelista' },
            { name: 'Basileo' },
            { name: 'Montserrat' },
            { name: 'Divina Misericordia' },
            { name: 'Catalina' },
            { name: 'Pio', holiday: { title: 'Día del niño', icon: 'fas fa-child' } }
        ]
    },
    {
        MONTH: 'Mayo',
        DAYS: [
            { name: 'Jeremias', holiday: { title: 'Día del Trabajo', icon: 'fas fa-tools' } },
            { name: 'Atanasio' },
            { name: 'Santa Cruz' },
            { name: 'Silviano' },
            { name: 'Ángel' },
            { name: 'Domingo' },
            { name: 'Benedicto' },
            { name: 'Bonifacio' },
            { name: 'Isaías' },
            { name: 'Antonino', holiday: { title: 'Día de las Madres', icon: 'fas fa-female' } },
            { name: 'Mayolo' },
            { name: 'Nereo' },
            { name: 'Fátima' },
            { name: 'Matías' },
            { name: 'Isidro', holiday: { title: 'Día del Maestro', icon: 'fas fa-chalkboard-teacher' } },
            { name: 'Ubaldo' },
            { name: 'Pascual' },
            { name: 'Claudia' },
            { name: 'Pedro Celestino' },
            { name: 'Bernardino' },
            { name: 'Cristóbal' },
            { name: 'Rita' },
            { name: 'Pentecostes' },
            { name: 'Maria Auxiliadora' },
            { name: 'Magdalena Sofia' },
            { name: 'Felipe Neri' },
            { name: 'Carolina' },
            { name: 'Germán' },
            { name: 'Maximino' },
            { name: 'Fernando' },
            { name: 'Visitación de la Virgen María' }
        ]
    },
    {
        MONTH: 'Junio',
        DAYS: [
            { name: 'Justino' },
            { name: 'Marcelino' },
            { name: 'Paula' },
            { name: 'Noemi' },
            { name: 'Marcia', holiday: { title: 'Día Mundial del Medio Ambiente', icon: 'fas fa-globe-americas' } },
            { name: 'Norberto' },
            { name: 'Isaac' },
            { name: 'Medardo' },
            { name: 'Efrén' },
            { name: 'Primitivo' },
            { name: 'Sagrado Corazón de Jesus' },
            { name: 'Inmaculado Corazón de María' },
            { name: 'Antonio de Padua' },
            { name: 'Anastasio' },
            { name: 'Yolanda' },
            { name: 'Santisima Trinidad' },
            { name: 'Ismael' },
            { name: 'Leoncio' },
            { name: 'Romualdo' },
            { name: 'Silverio' },
            { name: 'Luis' },
            { name: 'Paulino' },
            { name: 'Agripina' },
            { name: 'San Juan Bautista' },
            { name: 'Máximo' },
            { name: 'José María' },
            { name: 'Cirilo' },
            { name: 'Ireneo' },
            { name: 'Pedro y Pablo' },
            { name: 'Adolfo' }
        ]
    },
    {
        MONTH: 'Julio',
        DAYS: [
            { name: 'Aarón' },
            { name: 'Otón' },
            { name: 'Tomás' },
            { name: 'Refugio' },
            { name: 'Antonio' },
            { name: 'Rómulo' },
            { name: 'Fermín' },
            { name: 'Edgardo' },
            { name: 'Blanca' },
            { name: 'Apolonio' },
            { name: 'Plácido' },
            { name: 'Fortunato' },
            { name: 'Enrique' },
            { name: 'Camilo' },
            { name: 'Buenaventura' },
            { name: 'Carmen' },
            { name: 'Alejo' },
            { name: 'Federico' },
            { name: 'Áurea' },
            { name: 'Apolinar' },
            { name: 'Daniel' },
            { name: 'María Magdalena' },
            { name: 'Brigida' },
            { name: 'Charbel Makhluf' },
            { name: 'Santiago' },
            { name: 'Joaquín' },
            { name: 'Natalia' },
            { name: 'Victor' },
            { name: 'Marta' },
            { name: 'Leopoldo' },
            { name: 'Ignacio de Loyola' }
        ]
    },
    {
        MONTH: 'Agosto',
        DAYS: [
            { name: 'Alfonso' },
            { name: 'Gustavo' },
            { name: 'Rubén' },
            { name: 'Juan María Vianney' },
            { name: 'Nieves' },
            { name: 'Justo' },
            { name: 'Cayetano' },
            { name: 'Emiliano' },
            { name: 'Osvaldo' },
            { name: 'Lorenzo' },
            { name: 'Santa Clara de Asis' },
            { name: 'Hilaria' },
            { name: 'Ponciano' },
            { name: 'Maximiliano' },
            { name: 'Alba' },
            { name: 'Arsacio' },
            { name: 'Eusebio' },
            { name: 'Elena' },
            { name: 'Elvira' },
            { name: 'Bernardo' },
            { name: 'Victoria' },
            { name: 'Fabricio' },
            { name: 'Eleazar' },
            { name: 'Bartolomé' },
            { name: 'Patricia' },
            { name: 'Jacobo' },
            { name: 'Mónica' },
            { name: 'Agustín' },
            { name: 'Sabina' },
            { name: 'Rosa de Lima' },
            { name: 'Ramón' }
        ]
    },
    {
        MONTH: 'Septiembre',
        DAYS: [
            { name: 'Josué'},
            { name: 'Ingrid' },
            { name: 'Gregorio' },
            { name: 'Rosalía' },
            { name: 'Teresa de Calcuta' },
            { name: 'Zacarías' },
            { name: 'Regina' },
            { name: 'Natividad de la Virgen Maria' },
            { name: 'Doroteo' },
            { name: 'Nemesio' },
            { name: 'Elías' },
            { name: 'Pafnucio' },
            { name: 'Amado' },
            { name: 'Cipriano' },
            { name: 'Dolores' },
            { name: 'Cornelio' },
            { name: 'Adriana' },
            { name: 'Jacinto' },
            { name: 'Genaro' },
            { name: 'Eustaquio' },
            { name: 'Mateo' },
            { name: 'Mauricio' },
            { name: 'Guillermo' },
            { name: 'Merced' },
            { name: 'Cleofás' },
            { name: 'Florentino' },
            { name: 'Wenceslao' },
            { name: 'Miguel' },
            { name: 'Jerónimo' }
        ]
    },
    {
        MONTH: 'Octubre',
        DAYS: [
            { name: 'Santa Teresita del Niño Jesús'},
            { name: 'Angeles de la Guarda' },
            { name: 'Cándida' },
            { name: 'San Francisco de Asís' },
            { name: 'Faustina' },
            { name: 'Bruno' },
            { name: 'Rosario' },
            { name: 'Evodio' },
            { name: 'Dionisio' },
            { name: 'Samuel' },
            { name: 'Jaime' },
            { name: 'Pilar' },
            { name: 'Eduardo' },
            { name: 'Calixto' },
            { name: 'Teresa de Jesús' },
            { name: 'Margarita' },
            { name: 'Florencio' },
            { name: 'Lucas' },
            { name: 'Joel' },
            { name: 'Irene' },
            { name: 'Úrsula' },
            { name: 'Juan Pablo' },
            { name: 'Román' },
            { name: 'Fromundo' },
            { name: 'San Cripin' },
            { name: 'Evaristo' },
            { name: 'Frumencio' },
            { name: 'Judas Tadeo' },
            { name: 'Narciso' },
            { name: 'Claudio' },
            { name: 'Alonso', holiday: { title: 'Halloween', icon: 'fas fa-ghost' } }
        ]
    },
    {
        MONTH: 'Noviembre',
        DAYS: [
            { name: 'Floriberto', holiday: { title: 'Todos los Santos', icon: 'fas fa-menorah' } },
            { name: 'Basilio', holiday: { title: 'Fieles Difuntos', icon: 'fas fa-skull' } },
            { name: 'Tobias' },
            { name: 'Martín de Porres' },
            { name: 'Carlos Borromeo' },
            { name: 'Fibicio' },
            { name: 'Severo' },
            { name: 'Ernesto' },
            { name: 'Godofredo' },
            { name: 'Rafael' },
            { name: 'León Magno' },
            { name: 'Alicia' },
            { name: 'Josafat' },
            { name: 'Diego' },
            { name: 'Adeltrudis' },
            { name: 'Alberto Magno' },
            { name: 'Gertrudis' },
            { name: 'Lázaro' },
            { name: 'Felipa' },
            { name: 'Abdias' },
            { name: 'Edmundo' },
            { name: 'Agapio' },
            { name: 'Cecilia' },
            { name: 'Clemente' },
            { name: 'Cristo Rey' },
            { name: 'Erasmo' },
            { name: 'Fausto' },
            { name: 'Facundo' },
            { name: 'Valeriano' },
            { name: 'Saturnino' },
            { name: 'Andrés' }
        ]
    },
    {
        MONTH: 'Diciembre',
        DAYS: [
            { name: 'Eloy'},
            { name: 'Bibiana' },
            { name: 'Francisco Javier' },
            { name: 'Bárbara' },
            { name: 'Sabas' },
            { name: 'Nicolas' },
            { name: 'Ambrosio' },
            { name: 'Inmaculada Concepción de María' },
            { name: 'Juan Diego' },
            { name: 'Eustacio' },
            { name: 'Dárnaso' },
            { name: 'Sra. de Guadalupe' },
            { name: 'Lucía' },
            { name: 'Juan de la Cruz' },
            { name: 'Arturo' },
            { name: 'Adela' },
            { name: 'Modesto' },
            { name: 'Esperanza' },
            { name: 'Eva' },
            { name: 'Eugenio' },
            { name: 'Severino' },
            { name: 'Hungero' },
            { name: 'Ivón' },
            { name: 'Paula Elizabeth', holiday: { title: 'Nochebuena', icon: 'fas fa-tree' }  },
            { name: 'Belén', holiday: { title: 'Navidad', icon: 'fas fa-gifts' } },
            { name: 'Esteban' },
            { name: 'Fabiola' },
            { name: 'Santos Inocentes' },
            { name: 'Leonor' },
            { name: 'Judit' },
            { name: 'Silvestre', holiday: { title: 'Fin de año', icon: 'fas fa-calendar-times' } }
        ]
    },
]


export default SAINTS