const MODAL_TYPES = {
    SHOW_CONTENT: 'SHOW_FORM',
    SHOW_CONFIRMATION: 'SHOW_CONFIRMATION',
    SHOW_MESSAGE: 'SHOW_MESSAGE',
    SHOW_LOADER: 'SHOW_LOADER',
    CLOSE: 'CLOSE'
}

export { MODAL_TYPES };