const CALENDAR_TYPES = {
    SET_YEAR_MONTH: 'SET_YEAR_MONTH',
    SET_DATE: 'DATE'
}

const DASHBOARD_TYPES = {
    LIST_DASHBOARDS: 'LIST_DASHBOARDS',
    CREATE_DASHBOARD: 'CREATE_DASHBOARD',
    EDIT_DASHBOARD: 'EDIT_DASHBOARD',
    DELETE_DASHBOARD: 'DELETE_DASHBOARD',
    EDIT_GROUP: 'EDIT_GROUP',
    DELETE_GROUP: 'DELETE_GROUP',
    EDIT_TASK: 'EDIT_TASK',
    MOVE_TASK: 'MOVE_TASK',
    DELETE_TASK: 'DELETE_TASK',
    SET_IDX_DASHBOARD: 'SET_IDX_DASHBOARD'
}

export { CALENDAR_TYPES, DASHBOARD_TYPES };
