const CALENDAR_TYPES = {
    SET_YEAR_MONTH: 'SET_YEAR_MONTH',
    SET_DATE: 'DATE',
    TODAY_TASKS: 'TODAY_TASKS',
    LIST_TASKS: 'LIST_TASKS',
    CREATE_TASK: 'CREATE_TASK',
    EDIT_TASK: 'EDIT_TASK',
    DELETE:  {
        BY_DATE: 'DELETE_TASK_BY_DATE',
        BY_ID: 'DELETE_TASK_BY_ID'
    }
}

export { CALENDAR_TYPES };