const CALENDAR_TYPES = {
    SET_YEAR_MONTH: 'SET_YEAR_MONTH',
    SET_DATE: 'DATE',
    TODAY_TASKS: 'TODAY_TASKS',
    LIST_TASKS: 'LIST_TASKS',
    CREATE_TASK: 'CREATE_TASK',
    EDIT_TASK: 'EDIT_TASK',
    DELETE:  {
        BY_DATE: 'DELETE_TASK_BY_DATE',
        BY_ID: 'DELETE_TASK_BY_ID'
    }
}

const MODAL_TYPES = {
    SHOW_CONTENT: 'SHOW_FORM',
    SHOW_CONFIRMATION: 'SHOW_CONFIRMATION',
    SHOW_MESSAGE: 'SHOW_MESSAGE',
    SHOW_LOADER: 'SHOW_LOADER',
    CLOSE: 'CLOSE'
}

export { CALENDAR_TYPES, MODAL_TYPES };